### PR TITLE
Use Yarn instead of npm-shrinkwrap

### PR DESCRIPTION
**Pull request by mp4096**
I propose we use Yarn instead of `npm shrinkwrap` due to its deterministic dependency resolution algorithm [(ref)](https://code.facebook.com/posts/1840075619545360).

See also [this](http://stackoverflow.com/questions/40057469/what-is-the-difference-between-yarn-lock-and-npm-shrinkwrap) SO question.

### CODE REVIEW

**Comment by syxolk** [comment]
Ok, but once we go `yarn`, you never use `npm` ever again, since adding or removing dependencies automatically updates `yarn.lock`. We should make this clear in the README (install `npm install -g yarn` first).

**Comment by mp4096** [comment]
> Ok, but once we go yarn, you never use npm ever again, since adding or removing dependencies automatically updates yarn.lock.

Isn't parallel and non-mutually exclusive usage of `yarn` and `npm install` one of `yarn`'s selling points? [[ref]](https://yarnpkg.com/en/docs/migrating-from-npm)

> We should make this clear in the README (install npm install -g yarn first).
Yep, I'll update README. However, fb advises against install via `npm`: [[ref]](https://yarnpkg.com/en/docs/install#alternatives-tab)

**Comment by syxolk** [comment]
> Isn't parallel and non-mutually exclusive usage of yarn and npm install one of yarn's selling points?

I don't get your point. You must use `yarn add` and `yarn remove` instead of `npm install` and `npm uninstall`, otherwise `yarn.lock` is not updated accordingly.

**Comment by mp4096** [comment]
Are you sure? As far as I get it, `yarn` is based on the dep's list in `package.json`. If you want to add something, just add it to `package.json` and run `yarn`. If you want to upgrade the dependencies, run `yarn upgrade`. See [this comparison](https://yarnpkg.com/en/docs/migrating-from-npm#toc-cli-commands-comparison).

**Pull request merged**
