### PR TITLE
WIP: Big dependencies update

### PR DESCRIPTION
**Pull request by mp4096**
Ok, here we go again. Seems like a lot of packages are doing well, only two make problems:

* TypeScript 2.4.1 (2.4.0 works fine) causes a lot of import issues. See https://github.com/Microsoft/TypeScript/issues/16472 and https://github.com/Microsoft/TypeScript/issues/16772
* `eslint` changed its mind on indentation style, so we get a lot of lint errors

### CODE REVIEW

**Comment by mp4096** [comment]
@syxolk Can you check if 1b022514a792612cd5749392ab011dbf86920cc1 makes sense? Thanks!

**Comment by mp4096** [comment]
@syxolk Are we good to go?

**Comment by syxolk** [comment]
Looks good

**Comment by mp4096** [comment]
Thx!

**Pull request merged**
