### PR TITLE
Fix overlay z-index bug

### PR DESCRIPTION
**Pull request by mp4096**
Introduced during upgrade to spectre.css@0.2.9

@syxolk Do you think we should report it upstream or just fix it locally?

### CODE REVIEW

**Comment by syxolk** [comment]
This works for the About and Cancel dialog but it does not work here:

image

**Comment by mp4096** [comment]
Awww shit. Sorry, my bad for not testing properly.

I'll try to find a better `z-index` value tomorrow.

**Comment by mp4096** [comment]
Ok, seems like `spectre` uses 100, 200, 300 and 400 for `z-index` values. The overlay has 400, so I went for 300.

**Comment by mp4096** [comment]
Cool, thanks! Please squash and merge if good to go.

**Pull request merged**
