### PR TITLE
Responsive Image

### PR DESCRIPTION
**Pull request by syxolk**
For displays with a high resolution density this will only download larger images:

```
content:
- image:
    src: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/GitHub_logo_2013.svg/400px-GitHub_logo_2013.svg.png"
    srcset:
      https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/GitHub_logo_2013.svg/400px-GitHub_logo_2013.svg.png: 1x
      https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/GitHub_logo_2013.svg/800px-GitHub_logo_2013.svg.png: 2x
      https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/GitHub_logo_2013.svg/1600px-GitHub_logo_2013.svg.png: 4x
    alt: Github Logo
```

### CODE REVIEW

**Comment by mp4096** [comment]
Thanks! I'll review it till weekend.

In the meanwhile, stupid question: How does the app determine whether it should show `1x`/`2x`/`4x`? Is it something determined automatically by HTML5? Or does it depend on DPI? Or on the screen resolution? Is there also `8x` etc.?

**Comment by syxolk** [comment]
>  How does the app determine whether it should show 1x/2x/4x?

The `srcset` attribute is directly converted to ``  as explained here: https://software.intel.com/en-us/html5/hub/blogs/srcset-attribute-solving-responsive-image-dilemma/
The browser will then determine which image is downloaded and displayed.

It's also backwards-compatible because older browsers will just just the `src` attribute.

**Comment by syxolk** [comment]
Some good things I found with this implementation:
- It's backwards-compatible in YAML because `-image: <URL>` still works
- It closely resembles the HTML syntax -> There's no magic involved.
- We can set `alt` which is [required](https://www.w3.org/wiki/HTML/Elements/img#Requirements_for_providing_text_to_act_as_an_alternative_for_images)

Some shitty things;
- Maybe it's better to swap key and value for `srcset` -> `4x: http://example.org/image.png`
- It closely resembles the HTML syntax. It may be better to be more abstract. (`src` and the URL for `1x` will often be the same)

**Comment by syxolk** [comment]
Some ideas from our lovely contributors?

**Comment by mp4096** [comment]
Sorry for being late.

0. I've changed the example to include _visibly_ different pictures (I can't see any differences in the logo picture)
1. I have to read about responsive images first. Seems like I've conflated them with the [`<picture>` element](https://googlechrome.github.io/samples/picture-element/)
2. Concerning the YAML spec syntax:
    * I didn't know that `alt` is mandatory
    * I do think that the reversed key-value syntax is giga-weird and should be changed
    * I think that it is ok to break the backwards compatibility and make `image` a list with at least two elements, `1x` and `alt`.

So I imagine the YAML spec like this:
```yaml
- image:
    - description: A fluffy white cat  # this is mandatory
    - source_1x: snowflake.jpg  # this is also mandatory
    - source_2x: snowflake_large.jpg # optional
    - source_4x: snowflake_so_very_large.jpg # optional
```

**Comment by mp4096** [comment]
Sorry, got it wrong:
```yaml
- image:
    description: A fluffy white cat  # this is mandatory
    source_1x: snowflake.jpg  # this is also mandatory
    source_2x: snowflake_large.jpg # optional
    source_4x: snowflake_so_very_large.jpg # optional
```

**Comment by mp4096** [comment]
Thanks, the schema looks exactly how I wanted it to be! :+1: 

Unfortunately, I just cannot reproduce responsive images in Chromium. I've changed the DPR in the dev/responsive panel but I always get the small cat image. 

example

What am I doing wrong?

**Comment by syxolk** [comment]
It worked for me after clicking randomly different stuff for 5 minutes. (Chrome 57)

image

**Comment by syxolk** [comment]
Btw: You should reload the page after changing DPR settings.

Also for 4x:

image

**Comment by mp4096** [comment]
Oh, now I see. I could reproduce it by opening a new tab, going into the dev mode, setting the DPR first and only then loading the quiz.

**Comment by mp4096** [comment]
I'll change the hint in the example question and then you can merge this PR.

**Comment by mp4096** [comment]
If you think it's ready, that is.

**Comment by syxolk** [comment]
Chrome also seems to not fallback to 1x after it loaded the 4x image even if you go back to desktop mode (DPR=1).

But in some cases it does fallback. Really strange.

**Comment by mp4096** [comment]
Ok, LGTM :+1:

Merge at your discretion.

**Pull request merged**
